language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
  - TESTS=true
  matrix:
  - PACKAGE="aws-s3-async"     PINS="ppx_protocol_conv ppx_protocol_conv_json ppx_protocol_conv_xml_light aws-s3:. aws-s3-async:." OCAML_VERSION=4.05
  - PACKAGE="aws-s3-lwt"       PINS="ppx_protocol_conv ppx_protocol_conv_json ppx_protocol_conv_xml_light aws-s3:. aws-s3-lwt:."   OCAML_VERSION=4.05
  - PACKAGE="aws-s3-async"     PINS="ppx_protocol_conv ppx_protocol_conv_json ppx_protocol_conv_xml_light aws-s3:. aws-s3-async:." OCAML_VERSION=4.06
  - PACKAGE="aws-s3-lwt"       PINS="ppx_protocol_conv ppx_protocol_conv_json ppx_protocol_conv_xml_light aws-s3:. aws-s3-lwt:."   OCAML_VERSION=4.06

os:
  - linux
#  - osx
