language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
  - TESTS=true
  matrix:
  - PACKAGE="aws-s3"                                          OCAML_VERSION=4.05
  - PACKAGE="aws-s3-lwt"       PINS="aws-s3:. aws-s3-lwt:."   OCAML_VERSION=4.05
  - PACKAGE="aws-s3-async"     PINS="aws-s3:. aws-s3-async:." OCAML_VERSION=4.08
  - PACKAGE="aws-s3"                                          OCAML_VERSION=4.11
  - PACKAGE="aws-s3-lwt"       PINS="aws-s3:. aws-s3-lwt:."   OCAML_VERSION=4.11
  - PACKAGE="aws-s3-async"     PINS="aws-s3:. aws-s3-async:." OCAML_VERSION=4.11


os:
  - linux
#  - osx
