name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.12.0
          - 4.08.0
        concurrency:
          - async
          - lwt

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin . --no-action
      - run: opam depext aws-s3 aws-s3-${{ matrix.concurrency }} --yes --with-doc --with-test
      - run: opam install aws-s3 aws-s3-${{ matrix.concurrency }} --deps-only --with-doc --with-test
      - run: opam exec -- dune build aws-s3 aws-s3-${{ matrix.concurrency }}
      - run: opam exec -- dune runtest aws-s3 aws-s3-${{ matrix.concurrency }}
